import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const root = process.cwd();
const deployDir = join(root, "deploy/semantic-sidecar");
const input = join(deployDir, "python-requirements.in");
const wheelhouse = join(deployDir, "wheelhouse");
const lockPath = join(wheelhouse, "requirements.lock.txt");

function sha256(path: string): string {
  const hash = createHash("sha256");
  hash.update(readFileSync(path));
  return hash.digest("hex");
}

function parseWheelName(file: string): { name: string; version: string } | null {
  if (!file.endsWith(".whl")) return null;
  const parts = file.slice(0, -4).split("-");
  if (parts.length < 2) return null;
  return { name: parts[0]!.replace(/_/g, "-"), version: parts[1]! };
}

mkdirSync(wheelhouse, { recursive: true });
const download = spawnSync("python", [
  "-m",
  "pip",
  "download",
  "--only-binary=:all:",
  "--dest",
  wheelhouse,
  "-r",
  input,
], { stdio: "inherit" });
if (download.status !== 0) process.exit(download.status ?? 1);

const rows = readdirSync(wheelhouse)
  .filter((file) => file.endsWith(".whl"))
  .map((file) => {
    const parsed = parseWheelName(file);
    if (!parsed) throw new Error(`could not parse wheel filename: ${file}`);
    return { ...parsed, file, hash: sha256(join(wheelhouse, file)) };
  })
  .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));

const body = [
  "# Generated by npm run semantic:sidecar:prepare-wheelhouse.",
  "# Commit this lock only after review; do not commit wheel files.",
  ...rows.map((row) => `${row.name}==${row.version} --hash=sha256:${row.hash}`),
  "",
].join("\n");
writeFileSync(lockPath, body, "utf8");
console.log(`wrote ${lockPath} (${rows.length} wheels)`);
