/** Shared benchmark copy + numbers for the landing page and whitepaper. */
export const SWE_BENCH_SNAPSHOT = {
  reportVersion: "v1.1",
  reportTitle: "Repeated-work benchmark",
  benchmark: "SWE-bench Verified",
  benchmarkShort: "SWE-bench Verified",
  runName: "40-task paired benchmark",
  benchmarkTasks: 40,
  pairedRuns: 80,
  taskSeeds: 40,
  attempted: 40,
  completed: 40,
  pairedConditions: 2,
  baselineLabel: "Baseline agent",
  augmentedLabel: "TraceBase attached",
  harness: "mini-swe-agent v2.2.8 + Docker",
  model: "Fixed coding-agent stack",
  modelDisclosure: "Same model, temperature, tool budget, and Docker image in both arms",
  accuracyBaselinePct: 63,
  accuracyInjectionPct: 83,
  accuracyGainPp: 20,
  relativeAccuracyGainPct: 32,
  baselineResolved: 25,
  augmentedResolved: 33,
  newFixes: 8,
  regressions: 0,
  highConfidenceN: 26,
  highConfidenceSharePct: 65,
  stepReductionAvgPct: 26,
  stepReductionPeakPct: 65,
  costReductionAvgPct: 43,
  costReductionPeakPct: 70,
  bestTaskStepsBefore: 31,
  bestTaskStepsAfter: 11,
  bestTaskStepReductionPct: 65,
  bestTaskCostReductionPct: 70,
  bestTaskLabel: "best paired run",
  retrievalSignalCount: 6,
  patternFields: 3,
  stepCap: 40,
  costCapUsd: 1,
  dimensions: [
    { label: "Resolved", baseline: 63, tracebase: 83, unit: "%", delta: "+20 pp" },
    { label: "Cost", baseline: 100, tracebase: 57, unit: "index", delta: "-43%" },
    { label: "Steps", baseline: 100, tracebase: 74, unit: "index", delta: "-26%" },
    { label: "Regressions", baseline: 0, tracebase: 0, unit: "", delta: "0" },
  ],
  mechanismBreakdown: [
    { label: "Prior fix recalled", value: 44 },
    { label: "File rereads avoided", value: 24 },
    { label: "Loop / duplicate work cut", value: 20 },
    { label: "Shorter final patch path", value: 12 },
  ],
  qualityDimensions: [
    {
      label: "Correctness",
      baseline: 0.63,
      tracebase: 0.83,
      lift: "+32%",
      explanation:
        "Correctness asks the blunt question: did the patch actually fix the issue? TraceBase wins when prior mechanisms steer the agent away from plausible but wrong edits.",
    },
    {
      label: "Completeness",
      baseline: 0.52,
      tracebase: 0.76,
      lift: "+46%",
      explanation:
        "Completeness measures whether the agent covered the edge case, the call path, and the verification path rather than stopping at the first green-looking change.",
    },
    {
      label: "Best practices",
      baseline: 0.48,
      tracebase: 0.73,
      lift: "+52%",
      explanation:
        "Best practices score whether the patch follows the project shape. Memory helps because it carries the local way this codebase expects fixes to land.",
    },
    {
      label: "Code reuse",
      baseline: 0.40,
      tracebase: 0.70,
      lift: "+75%",
      explanation:
        "Code reuse is where repeated work compounds fastest: the agent reaches known helpers, known tests, and known failure paths instead of rediscovering them.",
    },
    {
      label: "Architectural fit",
      baseline: 0.45,
      tracebase: 0.71,
      lift: "+58%",
      explanation:
        "Architectural fit captures whether the solution belongs in the system, not just whether it passes locally. TraceBase gives the agent prior shape, not a blind patch.",
    },
  ],
} as const;
